name: Flutter Web Build and Deploy

on: 
  pull_request:
    branches:
      - main
      - feature/*

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      - run: flutter pub get
      - run: flutter build web --web-renderer html --base-href /${{ env.BRANCH_NAME }}/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build/web

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Notify Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v4
        with:
          script: |
            const pullRequestNumber = context.issue.number;
            const branchName = process.env.BRANCH_NAME;
            const pageUrl = `https://${{ github.repository_owner }}.github.io/${{ github.repository }}/${branchName}/`;
            const comment = `Preview URL for this branch: ${pageUrl}`;
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequestNumber,
              body: comment
            });
